### ISSUE TITLE
Crash in Lexer on '\' character

### ISSUE THREAD

**Issue by vdka** [trill-lang/trill#4]
Playing around in the app now, I imagine this is not limited to the app.
Crash occured at backslash in `printf("%d\`.

```
Lexer.readCharacter() throws -> UnicodeScalar at Sources/Parse/Lexer.swift:448
Lexer.advanceToNextToken() throws -> Token at Sources/Parse/Lexer.swift:505
Lexer.lex() throws -> [Token] at Sources/Parse/Lexer.swift:349
LexerTextStorage.processEditing() -> () at iOS App/AnnotatedTextStorage.swift:83
```

**Comment by harlanhaskins** [comment]
Thank you! Yep there are lots of small edge cases like this. I think I'm not handling EOF after Lexing the escape character. 😅

**Comment by harlanhaskins** [comment]
@vdka Try the latest master.

**Comment by harlanhaskins** [comment]
@vdka Is the issue fixed for you?

**Comment by vdka** [comment]
Sure is :+1:

**Comment by harlanhaskins** [comment]
Thanks for reporting! AFAIK you're the first stranger to download and try this project 😄 I'd love whatever feedback you have!
