### ISSUE TITLE
Arrays of strings crash LLVM

### ISSUE THREAD

**Issue by segiddins** [trill-lang/trill#40]
```
func main() {
  let x = ["1", "2", "3"]
  println(x)
  Mirror(reflecting: x).print(to: stdout)
  println("")
}
```

crashes when emitting an object file / running the JIT

**Comment by harlanhaskins** [comment]
The array implementation is ridiculously half-baked and bad. I actually think now that we bundle the stdlib that we should just make this an `AnyArray`, and soon after an `Array<T>`

**Comment by harlanhaskins** [comment]
Closing in favor of #59
