### ISSUE TITLE
Support for string interpolation

### ISSUE THREAD

**Issue by segiddins** [trill-lang/trill#47]
Probably the biggest challenge will be in the lexer, but this would be _very_ cool

**Comment by harlanhaskins** [comment]
100% down for this.

The question of syntax...

**Comment by harlanhaskins** [comment]
I'm thinking maybe bash-style, where you can do a simple variable substitution with a `$`, or a complex expression in `$()`

**Comment by harlanhaskins** [comment]
```swift
let a = 10
let s = "a: $a, a+1: $(a+1)"
```

Or just take Swift's, which I'm also absolutely cool with.

**Comment by segiddins** [comment]
My only issue with allowing `"$foo"` to interpolate `foo` is that it doesn't necessarily pass visually as a substitution, especially without syntax highlighting (balanced delimiters are really really cool)

**Comment by harlanhaskins** [comment]
Yeah I think you're right. Then the question becomes if we use `$()` or `\()`

I think if that's the option, I prefer `\()` because my eyes scan it as an escape sequence.

**Comment by segiddins** [comment]
String interpolation is implemented as of #52 !
